language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
install: pip install pytest pytest-cov coveralls --use-mirrors
script: py.test
after_success:
    - coveralls
notifications:
    email:
        - jturk@sunlightfoundation.com
