language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
install: pip install pytest pytest-cov coveralls
script: py.test --cov validictory --cov-config=.coveragerc
after_success:
    - coveralls
notifications:
    email:
        - james.p.turk@gmail.com
